stages:
  prepare_data:
    cmd: Disk/Yolo-Lite/Yolo-Lite/FurnitureDetection2.v3i.yolov8/data.yaml -d scripts/prepare_data.py
      -o data/processed python scripts/prepare_data.py
    deps:
    - /media/dhruv/Local
  train_model:
    cmd: python scripts/train.py
    deps:
    - cfg/yolov4-tiny-custom.cfg
    - data/processed
    - scripts/train.py
    outs:
    - models/yolov4-tiny/last.weights
    metrics:
    - models/yolov4-tiny/metrics.json
