stages:
  prepare_data:
    cmd: python scripts/prepare_data.py
    deps:
      - data/raw/data.yaml
      - scripts/prepare_data.py
    outs:
      - data/processed
  train_model:
    cmd: python scripts/train.py
    deps:
      - data/processed
      - scripts/train.py
      - cfg/yolov4-tiny-custom.cfg
    outs:
      - models/yolov4-tiny/last.weights
    metrics:
      - models/yolov4-tiny/metrics.json
  evaluate_model:
    cmd: python scripts/evaluate.py
    deps:
      - models/yolov4-tiny/last.weights
      - data/processed
      - scripts/evaluate.py
    metrics:
      - models/yolov4-tiny/eval_metrics.json
  export_model:
    cmd: python scripts/export.py
    deps:
      - models/yolov4-tiny/last.weights
      - scripts/export.py
    outs:
      - models/yolov4-tiny/yolov4-tiny.tflite
